import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.scss"
import NavBar from "@/components/NavBar"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <article>
                <main className={`${styles.main} ${inter.className}`}>
                    <section className={styles.firstSection}>
                        <div className={styles.container}>
                            <NavBar />
                        </div>
                    </section>
                </main>
            </article>
        </>
    )
}
